[project]
name = "ostrich"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhiram A R", email = "abhiramajithr@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "crewai[tools]>=1.15.14",
]

[project.scripts]
ostrich = "ostrich:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
